version: '3.1'
services:
  db:
    image: postgres:12-alpine
    ports:
      - '9999:5432'
    volumes:
          - ./data:/var/lib/postgres
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=12345


#  docker-compose -f docker-compose.yml up