version: 'alpine:3.14'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - .data:/var/lib/postgresql/data
    environment:

      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
